name: LGsignD
favicon: null
layout_spectrum: 0.74647
typography_spectrum: 0.82725
title: Handmade Knitted Dolls and Stuffed Animal Toys
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#573a28'
    - '#2a1510'
    - '#825e48'
    - '#ba8d6e'
    - '#e8c8a1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
