name: LGsignD
favicon: null
layout_spectrum: 0.74647
typography_spectrum: 0.82725
title: Handmade Knitted Dolls and Stuffed Animal Toys
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b376d4'
    - '#c3ad8d'
    - '#ffffff'
    - '#fee6fe'
    - '#c5a0d6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
