name: LGsignD
favicon: null
layout_spectrum: 0.958673699060455
typography_spectrum: 0.8062325823120773
title: Handmade Knitted Dolls and Stuffed Animal Toys
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5660763515625149
  lightness: 0.47393928235396743
  saturation: 0.2576674516312778
  rhythmicContrast: 0.738613958703354
purpose: []
