typography_spectrum: 0.82725
color:
  brandColors:
    - '#b376d4'
    - '#c3ad8d'
    - '#ffffff'
    - '#fee6fe'
    - '#c5a0d6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74647
analytics:
  google: null
  facebook: null
  twitter: null
name: LGsignD
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ABOUT
    id: 6f19d181-04b8-4840-a494-574948bf944d
    type: content
favicon: null
title: Handmade Knitted Dolls and Stuffed Animal Toys
purpose: []
