typography_spectrum: 0.5412299925466945
content_rating:
  adult: false
color:
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
  brandStrength: 0.2970216609787491
  lightness: 0.6481999053058243
  saturation: 0.6833093237382646
  rhythmicContrast: 0.23817184827272034
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d3f24056-7f2c-4184-9b91-01e7e562cdad.jpg
  type: null
  appId: null
layout_spectrum: 0.3253560966694967
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: LG Larsen
  email: deemiinovo@gmail.com
  url: 'https://thegrid.ai/lgsignd/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/35f6f633-d966-46f2-9671-2089d1fb6eae.jpg
name: LGsignD
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: CONTACT
    id: 22ae5d38-2a79-49bd-a831-c7a3f43cb7ac
    type: content
  - name: ONCE UPON a TIME....
    id: ce2b013c-7cc3-46db-ba36-865ed63ae25b
    type: content
  - name: PINK & BLUE
    id: ec6db6c8-d341-4ef9-80ae-7add7fb199b4
    type: content
  - name: ELF gnome
    id: d19938e0-5089-4077-b97b-6de2728387af
    type: content
  - name: elf NISSE
    id: 461041a6-6e4d-4112-b731-17d190aadb90
    type: content
  - name: SANTA claus
    id: f460536e-43cb-41bc-9df8-4f46bfaaf845
    type: content
  - name: SNOWman
    id: 56ffe300-1c57-4107-953f-2e038946be93
    type: content
  - name: TEDDY bear
    id: 364b47af-aecd-47be-b421-699709cac7ac
    type: content
  - name: boy MOUSE
    id: a9df4133-7470-425b-b4ed-eb1abe539e11
    type: content
  - name: girl MOUSE
    id: 52a99df8-1208-4c69-847f-31e186908db6
    type: content
  - name: ELEPHANT baby
    id: cebfa2f6-4366-4640-bce1-aa94d5e996a2
    type: content
  - name: LADYBIRD bug
    id: abbb9207-f4ec-4968-8029-e9b1c79571a4
    type: content
  - name: BUNNY rabbit
    id: 7d8a79c3-7e31-4cbb-b554-d55590a870dc
    type: content
  - name: Angel
    id: 1720eb9c-d6d8-41c5-95cf-cae522a8f1f6
    type: content
  - name: 'Lamb '
    id: 7c18940b-1a4a-4311-8817-d18c3c2d32db
    type: content
  - name: Bee
    id: a0829106-5a6a-4960-98ae-52301b4f42ae
    type: content
  - name: 'LGsamiCrafts :: home'
    url: 'https://thegrid.ai/lgsamicrafts/'
    type: external
  - name: 'OurFriends :: home'
    url: 'https://thegrid.ai/ourfriends/'
    type: external
  - name: 'LG :: home'
    url: 'https://thegrid.ai/lg-larsen/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c3f19788-ef3a-42b7-89eb-d5ac60eabbcb.jpg
title: Knitted Dolls  &  Stuffed Animal Toys
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/54683ea3-e92b-41a2-a225-d242ac34f535.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/54683ea3-e92b-41a2-a225-d242ac34f535.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Completely Made by Hand
purpose: []
